{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "fba13f87-41ae-4dd9-af74-6311ed9b01db",
   "metadata": {},
   "outputs": [],
   "source": [
    "from lvmtipo.actors import lvm\n",
    "\n",
    "sci = await lvm.sci.start()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "066a15b3-03b5-474d-9827-31e743d8d5ca",
   "metadata": {},
   "outputs": [],
   "source": [
    "from logging import DEBUG, INFO\n",
    "from sdsstools import get_logger\n",
    "logger = get_logger(\"test\")\n",
    "\n",
    "logger.sh.setLevel(INFO)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "6e40a731-0b85-40e1-a307-2f538d86a756",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"east\": {\"state\": \"integrating\", \"image_type\": \"object\", \"remaining_time\": 1.0, \"exposure_time\": 1.0, \"current_stack\": 1, \"n_stack\": 1}}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"west\": {\"state\": \"integrating\", \"image_type\": \"object\", \"remaining_time\": 1.0, \"exposure_time\": 1.0, \"current_stack\": 1, \"n_stack\": 1}}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"west\": {\"state\": \"reading\", \"image_type\": \"object\", \"remaining_time\": 0.0, \"exposure_time\": 1.0, \"current_stack\": 1, \"n_stack\": 1}}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"west\": {\"state\": \"done\", \"image_type\": \"object\", \"remaining_time\": 0.0, \"exposure_time\": 1.0, \"current_stack\": 1, \"n_stack\": 1}}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"west\": {\"state\": \"post_processing\", \"image_type\": \"object\"}}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"west\": {\"state\": \"written\", \"filename\": \"/data/lvm/sci/agcam/west/20220702/lvm.sci.agcam.west_00000002.fits\"}}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"east\": {\"state\": \"reading\", \"image_type\": \"object\", \"remaining_time\": 0.0, \"exposure_time\": 1.0, \"current_stack\": 1, \"n_stack\": 1}}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"east\": {\"state\": \"done\", \"image_type\": \"object\", \"remaining_time\": 0.0, \"exposure_time\": 1.0, \"current_stack\": 1, \"n_stack\": 1}}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"east\": {\"state\": \"post_processing\", \"image_type\": \"object\"}}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"east\": {\"state\": \"written\", \"filename\": \"/data/lvm/sci/agcam/east/20220702/lvm.sci.agcam.east_00000002.fits\"}}'\n",
      "\u001b[0;35m[DEBUG]: \u001b[0mb'{\"east\": {\"state\": \"idle\", \"filename\": \"/data/lvm/sci/agcam/east/20220702/lvm.sci.agcam.east_00000002.fits\"}, \"west\": {\"state\": \"idle\", \"filename\": \"/data/lvm/sci/agcam/west/20220702/lvm.sci.agcam.west_00000002.fits\"}}'\n",
      "\u001b[0;34m[INFO]: \u001b[0m{'east': {'state': 'idle', 'filename': '/data/lvm/sci/agcam/east/20220702/lvm.sci.agcam.east_00000002.fits'}, 'west': {'state': 'idle', 'filename': '/data/lvm/sci/agcam/west/20220702/lvm.sci.agcam.west_00000002.fits'}}\n",
      "Robust channel <RobustChannel \"amqp://guest:******@192.168.49.2:5672//#1\"> has been closed.\n",
      "NoneType: None\n",
      "Robust channel <RobustChannel \"amqp://guest:******@192.168.49.2:5672//#1\"> has been closed.\n",
      "NoneType: None\n",
      "Robust channel <RobustChannel \"amqp://guest:******@192.168.49.2:5672//#1\"> has been closed.\n",
      "NoneType: None\n",
      "Robust channel <RobustChannel \"amqp://guest:******@192.168.49.2:5672//#1\"> has been closed.\n",
      "NoneType: None\n",
      "Robust channel <RobustChannel \"amqp://guest:******@192.168.49.2:5672//#1\"> has been closed.\n",
      "NoneType: None\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: [Errno 111] Connect call failed ('192.168.49.2', 5672). Reconnecting after 5 seconds.\n",
      "Robust channel <RobustChannel \"amqp://guest:******@192.168.49.2:5672//#2\"> has been closed.\n",
      "NoneType: None\n",
      "Robust channel <RobustChannel \"amqp://guest:******@192.168.49.2:5672//#2\"> has been closed.\n",
      "NoneType: None\n",
      "\u001b[0;31m[ERROR]: \u001b[0mTraceback (most recent call last):\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/sdsstools/logger.py\"\u001b[39;49;00m, line \u001b[34m217\u001b[39;49;00m, in asyncio_exception_handler\n",
      "    \u001b[34mraise\u001b[39;49;00m exception\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_channel.py\"\u001b[39;49;00m, line \u001b[34m59\u001b[39;49;00m, in reopen\n",
      "    \u001b[34mawait\u001b[39;49;00m \u001b[36msuper\u001b[39;49;00m().reopen()\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/channel.py\"\u001b[39;49;00m, line \u001b[34m215\u001b[39;49;00m, in reopen\n",
      "    \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.initialize()\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_channel.py\"\u001b[39;49;00m, line \u001b[34m93\u001b[39;49;00m, in initialize\n",
      "    \u001b[34mawait\u001b[39;49;00m \u001b[36msuper\u001b[39;49;00m().initialize(timeout)\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/channel.py\"\u001b[39;49;00m, line \u001b[34m188\u001b[39;49;00m, in initialize\n",
      "    \u001b[36mself\u001b[39;49;00m._channel = \u001b[34mawait\u001b[39;49;00m asyncio.wait_for(\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/asyncio/tasks.py\"\u001b[39;49;00m, line \u001b[34m408\u001b[39;49;00m, in wait_for\n",
      "    \u001b[34mreturn\u001b[39;49;00m \u001b[34mawait\u001b[39;49;00m fut\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/channel.py\"\u001b[39;49;00m, line \u001b[34m178\u001b[39;49;00m, in _create_channel\n",
      "    \u001b[34mreturn\u001b[39;49;00m \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m._connection.connection.channel(\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aiormq/connection.py\"\u001b[39;49;00m, line \u001b[34m490\u001b[39;49;00m, in channel\n",
      "    \u001b[34mraise\u001b[39;49;00m \u001b[36mRuntimeError\u001b[39;49;00m(\u001b[33m\"\u001b[39;49;00m\u001b[33m%r\u001b[39;49;00m\u001b[33m closed\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m % \u001b[36mself\u001b[39;49;00m)\n",
      "\u001b[91mRuntimeError\u001b[39;49;00m: <Connection: \"amqp://guest:******@192.168.49.2:5672//\"> closed\n",
      "\n",
      "\u001b[0;31m[ERROR]: \u001b[0mTraceback (most recent call last):\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aiormq/channel.py\"\u001b[39;49;00m, line \u001b[34m136\u001b[39;49;00m, in rpc\n",
      "    result = \u001b[34mawait\u001b[39;49;00m asyncio.wait_for(\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/asyncio/tasks.py\"\u001b[39;49;00m, line \u001b[34m408\u001b[39;49;00m, in wait_for\n",
      "    \u001b[34mreturn\u001b[39;49;00m \u001b[34mawait\u001b[39;49;00m fut\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/asyncio/queues.py\"\u001b[39;49;00m, line \u001b[34m159\u001b[39;49;00m, in get\n",
      "    \u001b[34mawait\u001b[39;49;00m getter\n",
      "\u001b[91masyncio.exceptions.CancelledError\u001b[39;49;00m\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aiormq/base.py\"\u001b[39;49;00m, line \u001b[34m25\u001b[39;49;00m, in __inner\n",
      "    \u001b[34mreturn\u001b[39;49;00m \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.task\n",
      "\u001b[91masyncio.exceptions.CancelledError\u001b[39;49;00m\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/sdsstools/logger.py\"\u001b[39;49;00m, line \u001b[34m217\u001b[39;49;00m, in asyncio_exception_handler\n",
      "    \u001b[34mraise\u001b[39;49;00m exception\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_channel.py\"\u001b[39;49;00m, line \u001b[34m60\u001b[39;49;00m, in reopen\n",
      "    \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.restore()\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_channel.py\"\u001b[39;49;00m, line \u001b[34m78\u001b[39;49;00m, in restore\n",
      "    \u001b[34mawait\u001b[39;49;00m queue.restore(\u001b[36mself\u001b[39;49;00m)\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_queue.py\"\u001b[39;49;00m, line \u001b[34m65\u001b[39;49;00m, in restore\n",
      "    \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.consume(consumer_tag=consumer_tag, **kwargs)\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_queue.py\"\u001b[39;49;00m, line \u001b[34m127\u001b[39;49;00m, in consume\n",
      "    consumer_tag = \u001b[34mawait\u001b[39;49;00m \u001b[36msuper\u001b[39;49;00m().consume(\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/queue.py\"\u001b[39;49;00m, line \u001b[34m229\u001b[39;49;00m, in consume\n",
      "    \u001b[34mawait\u001b[39;49;00m asyncio.wait_for(\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/asyncio/tasks.py\"\u001b[39;49;00m, line \u001b[34m408\u001b[39;49;00m, in wait_for\n",
      "    \u001b[34mreturn\u001b[39;49;00m \u001b[34mawait\u001b[39;49;00m fut\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aiormq/channel.py\"\u001b[39;49;00m, line \u001b[34m422\u001b[39;49;00m, in basic_consume\n",
      "    \u001b[34mreturn\u001b[39;49;00m \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.rpc(\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aiormq/base.py\"\u001b[39;49;00m, line \u001b[34m168\u001b[39;49;00m, in wrap\n",
      "    \u001b[34mreturn\u001b[39;49;00m \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.create_task(func(\u001b[36mself\u001b[39;49;00m, *args, **kwargs))\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aiormq/base.py\"\u001b[39;49;00m, line \u001b[34m27\u001b[39;49;00m, in __inner\n",
      "    \u001b[34mraise\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.exception \u001b[34mfrom\u001b[39;49;00m \u001b[04m\u001b[36me\u001b[39;49;00m\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/asyncio/tasks.py\"\u001b[39;49;00m, line \u001b[34m650\u001b[39;49;00m, in _wrap_awaitable\n",
      "    \u001b[34mreturn\u001b[39;49;00m (\u001b[34myield from\u001b[39;49;00m awaitable.\u001b[32m__await__\u001b[39;49;00m())\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aiormq/base.py\"\u001b[39;49;00m, line \u001b[34m27\u001b[39;49;00m, in __inner\n",
      "    \u001b[34mraise\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.exception \u001b[34mfrom\u001b[39;49;00m \u001b[04m\u001b[36me\u001b[39;49;00m\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/asyncio/tasks.py\"\u001b[39;49;00m, line \u001b[34m650\u001b[39;49;00m, in _wrap_awaitable\n",
      "    \u001b[34mreturn\u001b[39;49;00m (\u001b[34myield from\u001b[39;49;00m awaitable.\u001b[32m__await__\u001b[39;49;00m())\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aiormq/base.py\"\u001b[39;49;00m, line \u001b[34m27\u001b[39;49;00m, in __inner\n",
      "    \u001b[34mraise\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.exception \u001b[34mfrom\u001b[39;49;00m \u001b[04m\u001b[36me\u001b[39;49;00m\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_connection.py\"\u001b[39;49;00m, line \u001b[34m132\u001b[39;49;00m, in connect\n",
      "    \u001b[34mawait\u001b[39;49;00m channel.reopen()\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_channel.py\"\u001b[39;49;00m, line \u001b[34m60\u001b[39;49;00m, in reopen\n",
      "    \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.restore()\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_channel.py\"\u001b[39;49;00m, line \u001b[34m78\u001b[39;49;00m, in restore\n",
      "    \u001b[34mawait\u001b[39;49;00m queue.restore(\u001b[36mself\u001b[39;49;00m)\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_queue.py\"\u001b[39;49;00m, line \u001b[34m65\u001b[39;49;00m, in restore\n",
      "    \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.consume(consumer_tag=consumer_tag, **kwargs)\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_queue.py\"\u001b[39;49;00m, line \u001b[34m127\u001b[39;49;00m, in consume\n",
      "    consumer_tag = \u001b[34mawait\u001b[39;49;00m \u001b[36msuper\u001b[39;49;00m().consume(\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/queue.py\"\u001b[39;49;00m, line \u001b[34m229\u001b[39;49;00m, in consume\n",
      "    \u001b[34mawait\u001b[39;49;00m asyncio.wait_for(\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/asyncio/tasks.py\"\u001b[39;49;00m, line \u001b[34m408\u001b[39;49;00m, in wait_for\n",
      "    \u001b[34mreturn\u001b[39;49;00m \u001b[34mawait\u001b[39;49;00m fut\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aiormq/channel.py\"\u001b[39;49;00m, line \u001b[34m418\u001b[39;49;00m, in basic_consume\n",
      "    \u001b[34mraise\u001b[39;49;00m DuplicateConsumerTag(\u001b[36mself\u001b[39;49;00m.number)\n",
      "\u001b[91maiormq.exceptions.DuplicateConsumerTag\u001b[39;49;00m: 2\n",
      "\n",
      "\u001b[0;31m[ERROR]: \u001b[0mTraceback (most recent call last):\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/sdsstools/logger.py\"\u001b[39;49;00m, line \u001b[34m217\u001b[39;49;00m, in asyncio_exception_handler\n",
      "    \u001b[34mraise\u001b[39;49;00m exception\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_channel.py\"\u001b[39;49;00m, line \u001b[34m59\u001b[39;49;00m, in reopen\n",
      "    \u001b[34mawait\u001b[39;49;00m \u001b[36msuper\u001b[39;49;00m().reopen()\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/channel.py\"\u001b[39;49;00m, line \u001b[34m215\u001b[39;49;00m, in reopen\n",
      "    \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.initialize()\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/robust_channel.py\"\u001b[39;49;00m, line \u001b[34m93\u001b[39;49;00m, in initialize\n",
      "    \u001b[34mawait\u001b[39;49;00m \u001b[36msuper\u001b[39;49;00m().initialize(timeout)\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/channel.py\"\u001b[39;49;00m, line \u001b[34m188\u001b[39;49;00m, in initialize\n",
      "    \u001b[36mself\u001b[39;49;00m._channel = \u001b[34mawait\u001b[39;49;00m asyncio.wait_for(\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/asyncio/tasks.py\"\u001b[39;49;00m, line \u001b[34m408\u001b[39;49;00m, in wait_for\n",
      "    \u001b[34mreturn\u001b[39;49;00m \u001b[34mawait\u001b[39;49;00m fut\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aio_pika/channel.py\"\u001b[39;49;00m, line \u001b[34m178\u001b[39;49;00m, in _create_channel\n",
      "    \u001b[34mreturn\u001b[39;49;00m \u001b[34mawait\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m._connection.connection.channel(\n",
      "  File \u001b[36m\"/opt/conda/lib/python3.10/site-packages/aiormq/connection.py\"\u001b[39;49;00m, line \u001b[34m490\u001b[39;49;00m, in channel\n",
      "    \u001b[34mraise\u001b[39;49;00m \u001b[36mRuntimeError\u001b[39;49;00m(\u001b[33m\"\u001b[39;49;00m\u001b[33m%r\u001b[39;49;00m\u001b[33m closed\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m % \u001b[36mself\u001b[39;49;00m)\n",
      "\u001b[91mRuntimeError\u001b[39;49;00m: <Connection: \"amqp://guest:******@192.168.49.2:5672//\"> closed\n",
      "\n",
      "Connection attempt to \"amqp://guest:******@192.168.49.2:5672//\" failed: 2. Reconnecting after 5 seconds.\n"
     ]
    }
   ],
   "source": [
    "from logging import DEBUG, INFO\n",
    "\n",
    "logger.sh.setLevel(DEBUG)\n",
    "\n",
    "def callback(reply):\n",
    "    logger.debug(f\"{reply.message.body}\")\n",
    "\n",
    "rc = await sci.agc.expose(1, callback=callback)\n",
    "logger.info(str(rc))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a46bb8da-7286-433a-8deb-7f62b78dd94e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
